### Returns the words count for each text version for the text with ID 60e43ccdcccde5ec63eee35c
GET http://localhost:5000/text/60e43ccdcccde5ec63eee35c/count

### Return Error Message when text ID is invalid
GET http://localhost:5000/text/invalidId123/count