### Submits a new Text and returns the created new text
POST http://localhost:5000/text/
content-type: application/json

{
"en": "one two three",
"fr": "un deux trois",
"ar": "واحد اثنان ثلاثة"
}

### Submits a new text even with missing text versions, returns the created new text
POST http://localhost:5000/text/
content-type: application/json

{
"en": "english text without french and arabic version"
}